# ═══════════════════════════════════════════
#  SERVER
# ═══════════════════════════════════════════
server.port=8080

# ═══════════════════════════════════════════
#  MONGODB  (replacing your PostgreSQL)
# ═══════════════════════════════════════════
spring.data.mongodb.uri=mongodb+srv://cemapaydn979_db_user:6MSckGXCFnKHTS3P@cluster0.xqay80f.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=aresdb
# ═══════════════════════════════════════════
#  JWT
# ═══════════════════════════════════════════
app.jwt.secret=AresProjectSecretKey2026@Bilkent#CS458
app.jwt.expiration=86400000

# ═══════════════════════════════════════════
#  GOOGLE OAUTH2  (your real credentials ✅)
# ═══════════════════════════════════════════
spring.security.oauth2.client.registration.google.client-id=624212981387-3oemopidfggtnvst949nujc7r211cejr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google


# ═══════════════════════════════════════════
#  EMAIL  (your Gmail credentials ✅)
# ═══════════════════════════════════════════
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yanlizenginar@gmail.com
spring.mail.password=vgcp ulhy hejn bdtk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ═══════════════════════════════════════════
#  APP SECRET
# ═══════════════════════════════════════════
app.secret-key=your-secret-key-here
# ═══════════════════════════════════════════
#  FACEBOOK OAUTH2
# ═══════════════════════════════════════════
spring.security.oauth2.client.registration.facebook.client-id=1014667905062807
spring.security.oauth2.client.registration.facebook.client-secret=4a7b74b57e53103f254939ec1ae8e6d8
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook
# ═══════════════════════════════════════════
#  CLAUDE AI (Anthropic)
# ═══════════════════════════════════════════
anthropic.api.key=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
anthropic.api.url=https://api.anthropic.com/v1/messages
anthropic.api.model=claude-3-haiku-20240307
# ═══════════════════════════════════════════
#  CORS
# ═══════════════════════════════════════════
app.cors.allowed-origins=http://localhost:3000

